name: Flatpak Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flatpak:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Flatpak
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder
    
    - name: Add Flathub remote
      run: |
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        
    - name: Install GNOME SDK
      run: |
        sudo flatpak install -y flathub org.gnome.Platform//47 org.gnome.Sdk//47
    
    - name: Build Flatpak
      run: |
        sudo flatpak-builder --repo=repo --force-clean build-dir dev.jaydoubleu.tweaks.lite.json
    
    - name: Verify build
      run: |
        sudo flatpak build-bundle repo tweaks-lite.flatpak dev.jaydoubleu.tweaks.lite
    
    - name: Upload Flatpak bundle
      uses: actions/upload-artifact@v4
      with:
        name: tweaks-lite-flatpak
        path: tweaks-lite.flatpak 