name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and run tests in Docker
      run: |
        docker build -t tweakslite-tests .
        docker run --rm -v ${PWD}:/coverage tweakslite-tests cp coverage.xml /coverage/

    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

    - name: Validate AppStream metadata
      run: |
        sudo apt-get update
        sudo apt-get install -y appstream-util
        appstream-util validate-relax --nonet data/dev.jaydoubleu.tweaks.lite.metainfo.xml.in
