name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and run tests in Docker
      run: |
        docker build -t tweakslite-tests .
        docker run --name test-run tweakslite-tests
        docker cp test-run:/app/coverage.xml ./coverage.xml
        docker rm test-run

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Validate AppStream metadata
      run: |
        sudo apt-get update
        sudo apt-get install -y appstream-util
        appstream-util validate-relax --nonet data/dev.jaydoubleu.tweaks.lite.metainfo.xml.in
